// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKifAt-xLE-hv1tMr0kCocmGzUQnEhB64',
    appId: '1:593798097129:android:a2cd152c5b5fde03ace878',
    messagingSenderId: '593798097129',
    projectId: 'agri-pro-ae630',
    storageBucket: 'agri-pro-ae630.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLL-Ytbh3cprTNXPO1rGgOur7q3PGXI0',
    appId: '1:593798097129:web:7ff9cb36a37bcbd5ace878',
    messagingSenderId: '593798097129',
    projectId: 'agri-pro-ae630',
    authDomain: 'agri-pro-ae630.firebaseapp.com',
    storageBucket: 'agri-pro-ae630.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlCLlYbSQVMM-xnZa3LDRdv55UL0srAi8',
    appId: '1:593798097129:ios:195d46d3dedf6366ace878',
    messagingSenderId: '593798097129',
    projectId: 'agri-pro-ae630',
    storageBucket: 'agri-pro-ae630.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlCLlYbSQVMM-xnZa3LDRdv55UL0srAi8',
    appId: '1:593798097129:ios:195d46d3dedf6366ace878',
    messagingSenderId: '593798097129',
    projectId: 'agri-pro-ae630',
    storageBucket: 'agri-pro-ae630.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlLL-Ytbh3cprTNXPO1rGgOur7q3PGXI0',
    appId: '1:593798097129:web:e61bd208fb89f545ace878',
    messagingSenderId: '593798097129',
    projectId: 'agri-pro-ae630',
    authDomain: 'agri-pro-ae630.firebaseapp.com',
    storageBucket: 'agri-pro-ae630.appspot.com',
  );

}